import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'

const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api'
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
function api(path,opts={}){const token=localStorage.getItem('token');return fetch(API+path,{headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...opts}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Request failed');return d})}

function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'))
 const [view,setView]=useState('shop'); const [products,setProducts]=useState([]); const [cart,setCart]=useState([]); const [msg,setMsg]=useState('')
 const logout=()=>{localStorage.clear();setUser(null);setView('shop')}
 useEffect(()=>{api('/products').then(setProducts).catch(()=>{})},[])
 const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{...p,quantity:1}]})
 const checkout=async()=>{if(!user){setMsg('Please login as a customer first.');return}try{await api('/orders/checkout',{method:'POST',body:JSON.stringify({items:cart.map(i=>({product_id:i.id,quantity:i.quantity}))})});setCart([]);setMsg('Order placed successfully and split into vendor sub-orders.')}catch(e){setMsg(e.message)}}
 return <><header><div className="brand">Code Commanders <span>Marketplace</span></div><nav><button onClick={()=>setView('shop')}>Shop</button>{user?.role==='customer'&&<button onClick={()=>setView('orders')}>My Orders</button>}{user?.role==='vendor'&&<button onClick={()=>setView('vendor')}>Vendor</button>}{user?.role==='admin'&&<button onClick={()=>setView('admin')}>Admin</button>}{user?<button className="outline" onClick={logout}>Logout</button>:<button className="primary" onClick={()=>setView('auth')}>Login / Register</button>}<span className="cart">🛒 {cart.reduce((a,x)=>a+x.quantity,0)}</span></nav></header><main>{msg&&<div className="notice">{msg}<button onClick={()=>setMsg('')}>×</button></div>}{view==='shop'&&<Shop products={products} add={add} cart={cart} checkout={checkout}/>} {view==='auth'&&<Auth onLogin={u=>{setUser(u);setView(u.role==='admin'?'admin':u.role==='vendor'?'vendor':'shop')}}/>}{view==='orders'&&<Orders/>}{view==='vendor'&&<Vendor/>}{view==='admin'&&<Admin/>}</main><footer>Multi-Vendor Marketplace • React + FastAPI + SQLAlchemy</footer></>
}
function Shop({products,add,cart,checkout}){return <section><div className="hero"><div><p className="eyebrow">UNIFIED STOREFRONT</p><h1>Shop from multiple vendors in one cart.</h1><p>Products, stock, vendor-wise fulfilment and commission tracking in one platform.</p></div><div className="heroCard"><b>{products.length}</b><span>live products</span><b>{money(cart.reduce((a,x)=>a+x.price*x.quantity,0))}</b><span>cart value</span></div></div><div className="grid">{products.map(p=><article className="card" key={p.id}><div className="productIcon">{p.category==='Electronics'?'🎧':'📦'}</div><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div className="row"><strong>{money(p.price)}</strong><span>{p.stock} in stock</span></div><button className="primary full" disabled={!p.stock} onClick={()=>add(p)}>Add to cart</button></article>)}</div>{cart.length>0&&<div className="cartPanel"><h2>Cart</h2>{cart.map(i=><div className="cartLine" key={i.id}><span>{i.name} × {i.quantity}</span><b>{money(i.price*i.quantity)}</b></div>)}<div className="cartTotal"><b>Total</b><b>{money(cart.reduce((a,x)=>a+x.price*x.quantity,0))}</b></div><button className="primary full" onClick={checkout}>Checkout</button></div>}</section>}
function Auth({onLogin}){const [mode,setMode]=useState('login');const [form,setForm]=useState({email:'',password:'',full_name:'',role:'customer'});const [err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{if(mode==='register'){await api('/auth/register',{method:'POST',body:JSON.stringify(form)})}const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:form.email,password:form.password})});localStorage.setItem('token',d.access_token);localStorage.setItem('user',JSON.stringify(d.user));onLogin(d.user)}catch(e){setErr(e.message)}};return <div className="auth card"><h2>{mode==='login'?'Welcome back':'Create account'}</h2>{err&&<p className="error">{err}</p>}<form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>{mode==='register'&&<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="customer">Customer</option><option value="vendor">Vendor</option></select>}<button className="primary full">{mode==='login'?'Login':'Register'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Need an account? Register':'Already registered? Login'}</button><div className="demo"><b>Demo accounts</b><br/>Admin: admin@codecommanders.local / Admin@123<br/>Vendor: vendor@codecommanders.local / Vendor@123<br/>Customer: customer@codecommanders.local / Customer@123</div></div>}
function Orders(){const [orders,setOrders]=useState([]);useEffect(()=>{api('/orders/my').then(setOrders).catch(()=>{})},[]);return <section><h1>My Orders</h1>{orders.length===0?<div className="empty">No orders yet.</div>:orders.map(o=><div className="card order" key={o.id}><div><b>Order #{o.id}</b><span>{new Date(o.created_at).toLocaleString()}</span></div><strong>{money(o.total_amount)}</strong><div className="suborders">{o.suborders.map(s=><span key={s.id}>Vendor {s.vendor_id}: {s.status}</span>)}</div><button onClick={async()=>{const reason=window.prompt('Dispute reason');if(!reason)return;const description=window.prompt('Describe the issue')||reason;try{await api('/disputes',{method:'POST',body:JSON.stringify({order_id:o.id,vendor_id:o.suborders[0]?.vendor_id,reason,description})});alert('Dispute submitted to platform admin.')}catch(e){alert(e.message)}}}>Raise Dispute</button></div>)}</section>}
function Vendor(){const [sum,setSum]=useState({});const [orders,setOrders]=useState([]);const [products,setProducts]=useState([]);const [form,setForm]=useState({name:'',description:'',price:'',stock:'',category:'Electronics'});const load=()=>{api('/vendor/summary').then(setSum);api('/vendor/orders').then(setOrders);api('/vendor/products').then(setProducts)};useEffect(load,[]);const add=async e=>{e.preventDefault();await api('/products',{method:'POST',body:JSON.stringify({...form,price:Number(form.price),stock:Number(form.stock)})});setForm({...form,name:'',description:'',price:'',stock:''});load()};const status=async(id,s)=>{await api(`/vendor/orders/${id}`,{method:'PATCH',body:JSON.stringify({status:s})});load()};return <section><h1>Vendor Dashboard</h1><div className="stats"><Stat t="Sales" v={money(sum.sales)}/><Stat t="Commission" v={money(sum.commission)}/><Stat t="Payout" v={money(sum.payout)}/><Stat t="Products" v={sum.products}/></div><div className="two"><div className="card"><h2>Add Product</h2><form onSubmit={add}><input placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input type="number" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><input type="number" placeholder="Stock" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} required/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><button className="primary full">List Product</button></form></div><div className="card"><h2>My Sub-orders</h2>{orders.map(o=><div className="tableRow" key={o.id}><span>#{o.id} / Order #{o.order_id}</span><b>{money(o.total)}</b><select value={o.status} onChange={e=>status(o.id,e.target.value)}><option>pending</option><option>processing</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></div>)}</div></div><div className="card"><h2>My Products</h2>{products.map(p=><div className="tableRow" key={p.id}><span>{p.name}</span><span>{money(p.price)}</span><span>Stock: {p.stock}</span></div>)}</div></section>}
function Stat({t,v}){return <div className="stat"><small>{t}</small><b>{v}</b></div>}
function Admin(){const [d,setD]=useState({});const [vs,setVs]=useState([]);const [ds,setDs]=useState([]);const load=()=>{api('/admin/dashboard').then(setD);api('/vendors').then(setVs);api('/admin/disputes').then(setDs)};useEffect(load,[]);const approve=async id=>{await api(`/admin/vendors/${id}/approve`,{method:'POST'});load()};const resolve=async id=>{await api(`/admin/disputes/${id}`,{method:'PATCH',body:JSON.stringify({status:'resolved',resolution:'Resolved by platform admin'})});load()};return <section><h1>Platform Admin Dashboard</h1><div className="stats"><Stat t="GMV" v={money(d.gmv)}/><Stat t="Commission" v={money(d.commission)}/><Stat t="Orders" v={d.orders}/><Stat t="Pending Vendors" v={d.pending_vendors}/></div><div className="two"><div className="card"><h2>Vendor Approval</h2>{vs.map(v=><div className="tableRow" key={v.id}><span>{v.business_name}</span><span>{v.category}</span>{v.approved?<span className="ok">Approved</span>:<button onClick={()=>approve(v.id)}>Approve</button>}</div>)}</div><div className="card"><h2>Disputes</h2>{ds.length?ds.map(x=><div className="tableRow" key={x.id}><span>#{x.id} {x.reason}</span><span>{x.status}</span>{x.status!=='resolved'&&<button onClick={()=>resolve(x.id)}>Resolve</button>}</div>):<div className="empty">No disputes.</div>}</div></div><div className="card"><h2>Vendor Sales</h2>{(d.vendor_sales||[]).map(v=><div className="bar" key={v.vendor}><span>{v.vendor}</span><div><i style={{width:`${d.gmv?Math.max(5,v.sales/d.gmv*100):5}%`}}/></div><b>{money(v.sales)}</b></div>)}</div></section>}

createRoot(document.getElementById('root')).render(<App/>)
